#!/bin/bash
#number of threads:
for  t  in  1 2 4 6 8
do
    # echo NUMT = $t
    # number of subdivisions:
    for s in  10  100  500 1000  5000 10000 25000 50000 75000 100000
    do
        # echo NUMS = $s
        g++   -DNUMTRIALS=$s   -DNUMT=$t   projectOne.cpp  -o prog -lm  -fopenmp
        ./prog
    done
done
